# Первое знакомсво с NumPy, SciPy и Matplotlib

## NumPy

In [2]:
import numpy as np

In [3]:
x=[2,3,4,6]
y=np.array(x)

In [5]:
print (type (x),x)
print (type (y),y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [6]:
print(x[1:3])

[3, 4]


In [7]:
print(y[1:3])

[3 4]


In [8]:
print(x[[0, 2]])

TypeError: list indices must be integers or slices, not list

In [9]:
print(y[[0, 2]])

[2 4]


In [10]:
print(y[y>3])

[4 6]


In [11]:
print(x*5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [12]:
print(y*5)

[10 15 20 30]


In [13]:
print(x**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [14]:
print(y**2)

[ 4  9 16 36]


In [18]:
matrix=[[1,2,4],[3,1,0]]
nd_array=np.array(matrix)

In [19]:
print(matrix[1][2])

0


In [21]:
print(nd_array[1,2])

0


In [25]:
print(np.random.rand())

0.2954615162520259


In [26]:
print(np.random.randn())

-0.7434278459289673


In [27]:
print(np.random.randn(4))

[-0.86806697  0.125051    0.15707334 -1.37388861]


In [28]:
print(np.random.randn(4,5))

[[ 0.73501234  0.18620659 -0.2151799   1.61122981 -0.79793119]
 [ 0.92571399  1.33895872 -0.52584733 -0.35835598 -0.05616357]
 [-1.71240763 -0.65095969 -0.85124609 -1.26186868 -1.45589188]
 [-0.29376802  1.06807036  0.93191628 -1.20750688  0.63026001]]


In [30]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


## SciPy

In [44]:
from scipy import optimize

In [46]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print(f([3.2, 0.1]))

3.0
